### ISSUE TITLE
performance comparison update

### ISSUE THREAD

**Issue by mrader1248** [linnanwang/BLASX#7]
The paper on the arXiv is already three years old. Which version of cuBLAS-XT was used to create the performance comparison charts? Is it still the case that BLASX is outperforming cuBLAS-XT? Wouldn't it be very interesting to have updated plots with current versions of cuBLAS-XT?

**Comment by linnanwang** [comment]
If you read the paper, you will notice that the main benefit of BLASX is from a built-in tile cache. This improves the performance up to 30% compared with the naive swapping scheme in cuBLAS-XT. The performance varies across GPUs and platforms. You can configure the makefile to get a personalized benchmark easily. 

Let me know if you meet difficulties in running the code. Thanks.
